display_name: Visualize IT
package_name: visualizeit

maintainer:
  name: AI
  email: a@com

priority: optional

section: x11

installed_size: 15700

dependencies:
  - libgstreamer1.0-dev 
  - libgstreamer-plugins-base1.0-dev
  - libgtk-3-dev
  - libgtk-3-0 
  - libblkid1 
  - liblzma5
  - libgcrypt20 
  - libgcrypt20-dev 
  - g++
  - liblz4-dev
  - liblzma5
  - libpangocairo-1.0-0 
  - libcairo2-dev 
  - libstdc++6

essential: false

#icon: linux/assets/apidash.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Visualize IT

generic_name: Visualize IT

categories:
  - Development
  - Utility

startup_notify: true